### PR TITLE
use Milla. Relax the requirement to use perl 5.6

### PR DESCRIPTION
**Pull request by miyagawa**
Rather than fixing Minilla to support 5.6 and further complicating the tool, this PR replaces the build tool to use Milla, and to relax the perl requirement down to 5.6.

This contradicts to #12. My personal take, as stated on #12, is that supporting 5.6 is a wasted effort, but this PR is just as minimal and Test::Requires probably doesn't need further development for a while (until Test::Builder is bumped to the newer infrastructure) and the current code can stay so long as it runs on 5.6 just fine.

### CODE REVIEW

**Comment by kentfredric** [comment]
:+1: :)

**Comment by tokuhirom** [comment]
I merged #12.

**Comment by shadowcat-mst** [comment]
Please don't. Many low level dists use Test::Requires and many of them support 5.6.

You're causing significant pain to the toolchain team for no good reason.

**Comment by shadowcat-mst** [comment]
If you don't want to maintain Test::Requires to the standard its users expected, I'd be happy to arrange for it to be adopted by the Perl-Toolchain-Gang organisation instead.

But killing 5.8 support for fun isn't fair.

**Pull request closed without merging**
